# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window1.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(637, 480)
        MainWindow.setMouseTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QGraphicsView(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(10, 10, 461, 441))
        self.image.setObjectName("image")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(540, 290, 50, 64))
        self.dial.setMaximum(360)
        self.dial.setSingleStep(10)
        self.dial.setPageStep(30)
        self.dial.setWrapping(True)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.lbl_turn = QtWidgets.QLabel(self.centralwidget)
        self.lbl_turn.setGeometry(QtCore.QRect(530, 360, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.lbl_turn.setFont(font)
        self.lbl_turn.setObjectName("lbl_turn")
        self.cntr_scl_x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.cntr_scl_x.setGeometry(QtCore.QRect(480, 200, 71, 22))
        self.cntr_scl_x.setMaximum(451.0)
        self.cntr_scl_x.setProperty("value", 225.0)
        self.cntr_scl_x.setObjectName("cntr_scl_x")
        self.cntr_scl_y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.cntr_scl_y.setGeometry(QtCore.QRect(560, 200, 71, 22))
        self.cntr_scl_y.setMaximum(431.0)
        self.cntr_scl_y.setProperty("value", 215.0)
        self.cntr_scl_y.setObjectName("cntr_scl_y")
        self.lbl_scale = QtWidgets.QLabel(self.centralwidget)
        self.lbl_scale.setGeometry(QtCore.QRect(530, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.lbl_scale.setFont(font)
        self.lbl_scale.setObjectName("lbl_scale")
        self.scale_slider = QtWidgets.QSlider(self.centralwidget)
        self.scale_slider.setGeometry(QtCore.QRect(500, 240, 131, 22))
        self.scale_slider.setOrientation(QtCore.Qt.Horizontal)
        self.scale_slider.setObjectName("scale_slider")
        self.lbl_scale_x = QtWidgets.QLabel(self.centralwidget)
        self.lbl_scale_x.setGeometry(QtCore.QRect(510, 180, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.lbl_scale_x.setFont(font)
        self.lbl_scale_x.setObjectName("lbl_scale_x")
        self.lbl_scale_y = QtWidgets.QLabel(self.centralwidget)
        self.lbl_scale_y.setGeometry(QtCore.QRect(590, 180, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.lbl_scale_y.setFont(font)
        self.lbl_scale_y.setObjectName("lbl_scale_y")
        self.btn_trans = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trans.setGeometry(QtCore.QRect(510, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.btn_trans.setFont(font)
        self.btn_trans.setObjectName("btn_trans")
        self.cntr_trans_y = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.cntr_trans_y.setGeometry(QtCore.QRect(560, 60, 71, 22))
        self.cntr_trans_y.setObjectName("cntr_trans_y")
        self.lbl_trans_x = QtWidgets.QLabel(self.centralwidget)
        self.lbl_trans_x.setGeometry(QtCore.QRect(510, 40, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.lbl_trans_x.setFont(font)
        self.lbl_trans_x.setObjectName("lbl_trans_x")
        self.cntr_trans_x = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.cntr_trans_x.setGeometry(QtCore.QRect(480, 60, 71, 22))
        self.cntr_trans_x.setObjectName("cntr_trans_x")
        self.lbl_trans_y = QtWidgets.QLabel(self.centralwidget)
        self.lbl_trans_y.setGeometry(QtCore.QRect(590, 40, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.lbl_trans_y.setFont(font)
        self.lbl_trans_y.setObjectName("lbl_trans_y")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(490, 400, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.btn_back.setFont(font)
        self.btn_back.setCheckable(False)
        self.btn_back.setObjectName("btn_back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Преобразование изображений"))
        self.lbl_turn.setText(_translate("MainWindow", "Поворот"))
        self.lbl_scale.setText(_translate("MainWindow", "Масштаб"))
        self.lbl_scale_x.setText(_translate("MainWindow", "X"))
        self.lbl_scale_y.setText(_translate("MainWindow", "Y"))
        self.btn_trans.setText(_translate("MainWindow", "Перенос"))
        self.lbl_trans_x.setText(_translate("MainWindow", "X"))
        self.lbl_trans_y.setText(_translate("MainWindow", "Y"))
        self.btn_back.setText(_translate("MainWindow", " В начало "))

